name: Odoo Addon Generate Readme

on:
  push:
    branches:
    - '[0-9]+.[0-9]+'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      
    - uses: actions/checkout@v2
      with:
        persist-credentials: false 
    - uses: nelonoel/branch-name@v1
    - uses: actions/setup-python@v2
      with:
        python-version: 3.8
    
    - name: Get Repository Metadata
      uses: octokit/request-action@v2.x
      id: metadata
      with:
        route: GET /repos/:repository
        repository: ${{ github.repository }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
    - uses: actions/cache@v1
      id: cache
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}
        restore-keys: |
          ${{ runner.os }}

    - name: Install OCA Maintainer Tools
      # if: steps.cache.outputs.cache-hit != 'true'
      run: |
        python -m pip install --upgrade pip
        pip install git+https://github.com/OCA/maintainer-tools.git#egg=maintainer-tools

    - name: Generate Readme, Icon and Table
      run: |
        git config --local user.email ${{ secrets.BOT_GITHUB_EMAIL }}
        git config --local user.name ${{ secrets.BOT_GITHUB_USER }}
        oca-gen-addons-table --commit
        oca-gen-addon-readme --commit --addons-dir=. --org-name=${{ github.event.repository.owner.name }} --repo-name=${{ github.event.repository.name }} --branch=${BRANCH_NAME}
        oca-gen-addon-icon --commit --addons-dir=.
    
  
    - name: Push
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.BOT_GITHUB_TOKEN }}
        branch: ${{ github.ref }}
      env:
        GITHUB_ACTOR: ${{ secrets.BOT_GITHUB_USER }}
